### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by henrychen11** [henrychen11/liqr#2]

**Comment by s-pangburn** [comment]
Your login form is very attractive and polished! Great work Henry! Just a few points for general refinement:

- [ ] liqr logo should be a little bigger and more prominent. Right now it looks smaller than the Login and Signup buttons which looks a little wrong.
- [ ] Your "Demo" button should have the same hover effect as your login and signup buttons.
- [ ] Login and Signup buttons should stretch from top to bottom of the navbar. Right now when you hover over them it becomes clear there's a small sliver at the bottom the button doesn't cover. Distracting.
- [ ] "Need an account? Sign up" <- Sign up should lighten slightly on hover, same with "Already registered? Login". I think they darken right now, but they are already so dark it's hard to tell, so you should go the other direction and make them more gray.
- [ ] Errors should be red, and the text should have just a little bit more padding on top.
- [ ] All your nav buttons should stretch from the top to the bottom of the navbar.
- [ ] Going to a random url (`https://liqr.herokuapp.com/#/lsdfkjdsfh`) should redirect to login. Hint: use a `<Switch>` and a `<Redirect>`!

**Comment by henrychen11** [comment]
Hey Stephen,

Thanks for your great feedback. I have just patching up the item you listed
in this email. Running through some checks before submitting my first MVP.
Should be assigning that tonight. Thank you.

Henry

**Comment by henrychen11** [comment]
Finished revisions

**Comment by s-pangburn** [comment]
Looks good! I'll mark this as complete! 👍
