### ISSUE TITLE
Review Photo MVP

### ISSUE THREAD

**Issue by henrychen11** [henrychen11/liqr#4]
User can upload, edit/update, and delete photo

**Comment by s-pangburn** [comment]
- [ ] Input/textarea elements in your creation and edit forms should have more padding
- [ ] I should not be able to submit a photo without a title
- [ ] The pop-up title that appears on hover for each item on the index page should be a clickable link, or at the very least, the title should be.
- [ ] Make your photos smaller so they load faster (very important!)

**Comment by henrychen11** [comment]
Issues fixed for new photo form also downsized images to under 200KB each.
Current database seed is 40 images total about 7 MB. Slow loading problem
still exists.

**Comment by s-pangburn** [comment]
Awesome job Henry! The page seems to load lightning fast for me now, so whatever you did, it worked! 👍
