### ISSUE TITLE
Comments MVP

### ISSUE THREAD

**Issue by henrychen11** [henrychen11/liqr#6]
User can create comments and only delete comments they wrote.

**Comment by s-pangburn** [comment]
- [ ] Comments should either have more padding from the border or no border at all.
- [ ] I should be able to edit a comment
- [ ] Delete comment icon should `cursor: pointer` on hover

**Comment by henrychen11** [comment]
Working on editing / updating comment

**Comment by henrychen11** [comment]
users can successfully edit comments now

**Comment by s-pangburn** [comment]
Make sure the textarea in the edit form autofocuses, but otherwise, I'll consider this feature complete 👍

**Comment by henrychen11** [comment]
Autofocus feature added to input area
